### ISSUE TITLE
Crashes during fetch stage when attempting to harvest

### ISSUE THREAD

**Issue by anotheredward** [openresearchdata/ckanext-oaipmh#20]
Crashes during fetch stage due to not calling `check_access`
On attempting to harvest the following endpoint:
https://api.figshare.com/v2/oai

With the following settings:
```json
{ 
  "credentials": null,
  "metadata_prefix": "oai_dc"
}
```

**Comment by metaodi** [comment]
This seems to be a CKAN compatibility issue, I'll look into that.

**Comment by camfindlay** [comment]
Thanks @metaodi (Cam from the ckan dev list here) also... @anotheredward is working with us on this.

**Comment by camfindlay** [comment]
Let us know how you go with getting an initial CKAN 2.7+ compatible version - we can likely help with some peer review.

**Comment by metaodi** [comment]
@camfindlay @anotheredward I could successfully harvest figshare using my changes from #21 (altough I only used a subset, to reduce the number of datasets for debugging). Maybe you can have a look at my PR and tell me if this works for you as well.
